name: Deployment

on: 
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Cache Node.js modules
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true' || hashFiles('**/package.json', '**/package-lock.json') != ''
              run: npm ci

            - name: Build and deploy
              run: |
                echo "Building and deploying the application..."
                # Add your build and deployment commands here